
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Aluno
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form ex2
     */
    public Cliente() {
        initComponents();
    }
    String usuario = "root";
    String senha = "";
    String url = "jdbc:mysql://127.0.0.1:3306/exercicio_11_05";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEnd = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        lblCel = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        lblTel = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setResizable(false);
        getContentPane().setLayout(null);

        lblId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblId.setText("ID");
        getContentPane().add(lblId);
        lblId.setBounds(20, 110, 12, 15);

        txtId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtId);
        txtId.setBounds(80, 110, 720, 21);

        lblCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCpf.setText("CPF");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(830, 110, 24, 15);

        txtCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtCpf);
        txtCpf.setBounds(870, 110, 260, 21);

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(20, 150, 34, 15);

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtNome);
        txtNome.setBounds(80, 150, 1050, 21);

        lblEnd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEnd.setText("Endereço");
        getContentPane().add(lblEnd);
        lblEnd.setBounds(20, 190, 53, 15);

        txtEnd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtEnd);
        txtEnd.setBounds(80, 190, 1050, 21);

        lblCel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCel.setText("Celular");
        getContentPane().add(lblCel);
        lblCel.setBounds(20, 230, 40, 15);

        txtCel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtCel);
        txtCel.setBounds(80, 230, 255, 21);

        lblTel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTel.setText("Telefone");
        getContentPane().add(lblTel);
        lblTel.setBounds(360, 230, 48, 15);

        txtTel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtTel);
        txtTel.setBounds(420, 230, 255, 21);

        lblEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEmail.setText("Email");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(20, 270, 32, 15);

        txtEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(80, 270, 1050, 21);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "E-mail", "CPF", "Endereço", "Telefone", "Celular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jScrollPane2.setViewportView(tblCliente);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 320, 1110, 320);

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Consultar_Cliente.png"))); // NOI18N
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(20, 10, 70, 80);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar_Cliente.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(100, 10, 80, 80);

        btnAdicionar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cadastrar_Cliente.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(190, 10, 80, 80);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Limpar_Cliente.png"))); // NOI18N
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(280, 10, 80, 80);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Excluir_Cliente.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(370, 10, 80, 80);

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Voltar_Cliente.png"))); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(460, 10, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundo_Cliente.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 690);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1150, 690);

        setSize(new java.awt.Dimension(1166, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = Integer.parseInt(txtId.getText());

        String sql = "delete cliente where id=?";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setInt(1, id);

            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Cliente removido com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na remoção dos dados do usuário");
        }

        txtTel.setText(null);
        txtCpf.setText(null);
        txtEnd.setText(null);
        txtEmail.setText(null);
        txtNome.setText(null);
        txtCel.setText(null);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int id = Integer.parseInt(txtId.getText());
        String Email = txtEmail.getText();
        String cpf = txtCpf.getText();
        String end = txtEnd.getText();
        String tel = txtTel.getText();
        String nome = txtNome.getText();
        String cel = txtCel.getText();

        String sql = "update cliente set nome=?, email=?,cpf=?, endereco=?, telefone=?, celular=? where id=?";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setString(1, nome);
            comando.setString(2, Email);
            comando.setString(3, cpf);
            comando.setString(4, end);
            comando.setString(5, tel);
            comando.setString(6, cel);

            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao editar dos dados de cadastro do usuário");
        }

        txtTel.setText(null);
        txtCpf.setText(null);
        txtEnd.setText(null);
        txtEmail.setText(null);
        txtNome.setText(null);
        txtCel.setText(null);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
