
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Estevam
 */
public class Materiais extends javax.swing.JFrame {

    /**
     * Creates new form ex4
     */
    public Materiais() {
        initComponents();
    }

    String usuario = "root";
    String senha = "";
    String url = "jdbc:mysql://127.0.0.1:3306/exercicio_11_05";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblDtCadastro = new javax.swing.JLabel();
        txtDtCad = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtVal = new javax.swing.JTextField();
        lblDescrição = new javax.swing.JLabel();
        txtDescrição = new javax.swing.JTextField();
        lblMateriaPrima = new javax.swing.JLabel();
        jcbMateriaPrima = new javax.swing.JComboBox<>();
        sPedido = new javax.swing.JScrollPane();
        tblMateriais = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCadSer = new javax.swing.JToggleButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Materiais");
        setResizable(false);
        getContentPane().setLayout(null);

        lblID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblID.setText("ID");
        getContentPane().add(lblID);
        lblID.setBounds(20, 120, 12, 15);
        getContentPane().add(txtID);
        txtID.setBounds(110, 120, 430, 20);

        lblDtCadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDtCadastro.setText("Data Cadastro");
        getContentPane().add(lblDtCadastro);
        lblDtCadastro.setBounds(570, 120, 90, 15);
        getContentPane().add(txtDtCad);
        txtDtCad.setBounds(660, 120, 460, 20);

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome Material");
        getContentPane().add(lblNome);
        lblNome.setBounds(20, 160, 80, 15);
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 160, 1010, 20);

        lblValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblValor.setText("Valor M²");
        getContentPane().add(lblValor);
        lblValor.setBounds(20, 200, 70, 15);
        getContentPane().add(txtVal);
        txtVal.setBounds(110, 200, 430, 20);

        lblDescrição.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDescrição.setText("Descrição");
        getContentPane().add(lblDescrição);
        lblDescrição.setBounds(20, 240, 56, 15);

        txtDescrição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriçãoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescrição);
        txtDescrição.setBounds(110, 240, 1010, 100);

        lblMateriaPrima.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMateriaPrima.setText("Matéria Prima:");
        getContentPane().add(lblMateriaPrima);
        lblMateriaPrima.setBounds(570, 200, 80, 15);

        jcbMateriaPrima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adesivo", "Lona", "Papel", "Adesivo Recorte" }));
        getContentPane().add(jcbMateriaPrima);
        jcbMateriaPrima.setBounds(660, 200, 120, 20);

        tblMateriais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data Serviço", "Valor Serviço", "Nome Cliente", "CPF Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sPedido.setViewportView(tblMateriais);

        getContentPane().add(sPedido);
        sPedido.setBounds(20, 360, 1110, 300);

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\ExercicioAula13_04\\src\\Consultar_Cliente.png")); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(20, 10, 70, 80);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar_Cliente.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(100, 10, 80, 80);

        btnCadSer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cadastrar_Servicos.png"))); // NOI18N
        btnCadSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadSerActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadSer);
        btnCadSer.setBounds(190, 10, 80, 80);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Limpar_Cliente.png"))); // NOI18N
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(280, 10, 80, 80);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Excluir_Cliente.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(370, 10, 80, 80);

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Voltar_Cliente.png"))); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(460, 10, 80, 80);

        txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundo_Cliente.png"))); // NOI18N
        getContentPane().add(txt);
        txt.setBounds(0, 0, 1150, 690);

        setSize(new java.awt.Dimension(1166, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadSerActionPerformed
        // TODO add your handling code here:

        String dt = txtDtCad.getText();
        String nome = txtNome.getText();
        String cpf = txtDescrição.getText();
        Double val = Double.parseDouble(txtVal.getText());

        DefaultTableModel pedido = (DefaultTableModel) tblMateriais.getModel();

        Object[] ped = new Object[5];

        ped[0] = dt;
        ped[1] = val;
        ped[2] = nome;
        ped[3] = cpf;

        pedido.addRow(ped);

        JOptionPane.showMessageDialog(null, "Pedido Cadastrado com Sucesso!");

        txtDtCad.setText(null);
        txtNome.setText(null);
        txtDescrição.setText(null);
        txtVal.setText(null);
    }//GEN-LAST:event_btnCadSerActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = Integer.parseInt(txtId.getText());

        String sql = "delete material where id=?";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setInt(1, id);

            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Cliente removido com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na remoção dos dados do usuário");
        }

        txtDtCad.setText(null);
        txtDescrição.setText(null);
        txtVal.setText(null);
        txtNome.setText(null);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String sql = "select * from materiais order by nome";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            ResultSet resultado = comando.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) tblMateriais.getModel();

            //Limpar a tabela da tela
            //Capturar o total de linhas da tebela da tela.
            int totalDeLinhas = modelo.getRowCount();

            for (int p = 0; p < totalDeLinhas; p++) {
                //Remove a linha da tabela ba posição informada.
                modelo.removeRow(p);
            }

            while (resultado.next()) {
                Object[] linha = new Object[]{
                    resultado.getInt("ID"),
                    resultado.getString("DtCad"),
                    resultado.getString("Nome"),
                    resultado.getString("Val"),
                    resultado.getString("tipoServico"),};

                modelo.addRow(linha);
            }
            txtID.setText(null);
            txtDtCad.setText(null);
            txtNome.setText(null);
            txtVal.setText(null);
            jcbMateriaPrima.null);
            txtDescrição.setText(null);

            resultado.close();
            comando.close();
            conexao.close();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na consulta de dados");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtDescriçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriçãoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materiais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadSer;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jcbMateriaPrima;
    private javax.swing.JLabel lblDescrição;
    private javax.swing.JLabel lblDtCadastro;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMateriaPrima;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblValor;
    private javax.swing.JScrollPane sPedido;
    private javax.swing.JTable tblMateriais;
    private javax.swing.JLabel txt;
    private javax.swing.JTextField txtDescrição;
    private javax.swing.JTextField txtDtCad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtVal;
    // End of variables declaration//GEN-END:variables
}
