
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Estevam
 */
public class Materiais extends javax.swing.JFrame {

    /**
     * Creates new form ex4
     */
    public Materiais() {
        initComponents();
    }

    String usuario = "root";
    String senha = "";
    String url = "jdbc:mysql://127.0.0.1:3306/grafica";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblDtCad = new javax.swing.JLabel();
        txtDtCad = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblVal = new javax.swing.JLabel();
        txtVal = new javax.swing.JTextField();
        lblMateriaPrima = new javax.swing.JLabel();
        jcbMateriaPrima = new javax.swing.JComboBox<>();
        lblDescrição = new javax.swing.JLabel();
        txtDescrição = new javax.swing.JTextField();
        jspMateriais = new javax.swing.JScrollPane();
        tblMateriais = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JToggleButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Materiais");
        setResizable(false);
        getContentPane().setLayout(null);

        lblID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblID.setText("ID");
        getContentPane().add(lblID);
        lblID.setBounds(20, 120, 12, 15);
        getContentPane().add(txtID);
        txtID.setBounds(110, 120, 430, 30);

        lblDtCad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDtCad.setText("Data Cadastro");
        getContentPane().add(lblDtCad);
        lblDtCad.setBounds(570, 120, 90, 15);
        getContentPane().add(txtDtCad);
        txtDtCad.setBounds(660, 120, 460, 30);

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome Material");
        getContentPane().add(lblNome);
        lblNome.setBounds(20, 170, 80, 15);
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 170, 1010, 30);

        lblVal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblVal.setText("Valor M²");
        getContentPane().add(lblVal);
        lblVal.setBounds(20, 220, 70, 15);
        getContentPane().add(txtVal);
        txtVal.setBounds(110, 220, 430, 30);

        lblMateriaPrima.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMateriaPrima.setText("Matéria Prima");
        getContentPane().add(lblMateriaPrima);
        lblMateriaPrima.setBounds(570, 220, 80, 15);

        jcbMateriaPrima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adesivo", "Lona", "Papel", "Adesivo Recorte" }));
        getContentPane().add(jcbMateriaPrima);
        jcbMateriaPrima.setBounds(660, 220, 150, 30);

        lblDescrição.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDescrição.setText("Descrição");
        getContentPane().add(lblDescrição);
        lblDescrição.setBounds(20, 270, 56, 15);

        txtDescrição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriçãoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescrição);
        txtDescrição.setBounds(110, 270, 1010, 100);

        tblMateriais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Material", "Valor M²", "Matéria Prima"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspMateriais.setViewportView(tblMateriais);

        getContentPane().add(jspMateriais);
        jspMateriais.setBounds(20, 390, 1110, 270);

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Consultar_Materiais.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(20, 10, 70, 80);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar_Cliente.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(100, 10, 80, 80);

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cadastrar_Servicos.png"))); // NOI18N
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(190, 10, 80, 80);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Limpar_Cliente.png"))); // NOI18N
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(280, 10, 80, 80);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Excluir_Cliente.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(370, 10, 80, 80);

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Voltar_Cliente.png"))); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(460, 10, 80, 80);

        txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundo_Cliente.png"))); // NOI18N
        getContentPane().add(txt);
        txt.setBounds(0, 0, 1150, 690);

        setSize(new java.awt.Dimension(1166, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:

        String datacadastro = txtDtCad.getText();
        String nome = txtNome.getText();
        Double precom2 = Double.parseDouble(txtVal.getText());
        int MateriaPrima_cod_MateriaPrima = 1;
        String descricao = txtDescrição.getText();
        
            String sql = "insert into usuario values (?, ?, ?, ?, ?) ";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setInt(1, MateriaPrima_cod_MateriaPrima);
            comando.setString(2, descricao);
            comando.setString(3, nome);
            comando.setString(4, datacadastro);
            comando.setDouble(5, precom2);

            
            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Material cadastrado com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na inserção dos dados cadastrais do material");
        }

        txtDtCad.setText(null);
        txtNome.setText(null);
        txtVal.setText(null);
      // Material(null);
        txtDescrição.setText(null);
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = Integer.parseInt(txtID.getText());

        String sql = "delete material where id=?";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setInt(1, id);

            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Material removido com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na remoção dos dados do material");
        }

        txtDtCad.setText(null);
        txtDescrição.setText(null);
        txtVal.setText(null);
        txtNome.setText(null);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String sql = "select * from materiais order by nome";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            ResultSet resultado = comando.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) tblMateriais.getModel();

            //Limpar a tabela da tela
            //Capturar o total de linhas da tebela da tela.
            int totalDeLinhas = modelo.getRowCount();

            for (int p = 0; p < totalDeLinhas; p++) {
                //Remove a linha da tabela ba posição informada.
                modelo.removeRow(p);
            }

            while (resultado.next()) {
                Object[] linha = new Object[]{
                    resultado.getInt("ID"),
                    resultado.getString("dt_cadastro"),
                    resultado.getString("nome_material"),
                    resultado.getString("valor"),
                    resultado.getString("mat_prima"),
                    resultado.getString("descricao")
                        
                };
                
               
        

                modelo.addRow(linha);
            }
            txtID.setText(null);
            txtDtCad.setText(null);
            txtNome.setText(null);
            txtVal.setText(null);
            jcbMateriaPrima.setSelectedIndex(0);
            txtDescrição.setText(null);

            resultado.close();
            comando.close();
            conexao.close();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na consulta do material");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtDescriçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriçãoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materiais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jcbMateriaPrima;
    private javax.swing.JScrollPane jspMateriais;
    private javax.swing.JLabel lblDescrição;
    private javax.swing.JLabel lblDtCad;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMateriaPrima;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblVal;
    private javax.swing.JTable tblMateriais;
    private javax.swing.JLabel txt;
    private javax.swing.JTextField txtDescrição;
    private javax.swing.JTextField txtDtCad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtVal;
    // End of variables declaration//GEN-END:variables
}
