/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marqu
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbUsuario = new javax.swing.JButton();
        jbCliente = new javax.swing.JButton();
        jbMatPrima = new javax.swing.JButton();
        jbMaterial = new javax.swing.JButton();
        jbServiço = new javax.swing.JButton();
        jbOrcamento = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        getContentPane().setLayout(null);

        jbUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Menu\\Usuário_Menu.png")); // NOI18N
        jbUsuario.setOpaque(false);
        getContentPane().add(jbUsuario);
        jbUsuario.setBounds(80, 70, 120, 120);

        jbCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Menu\\Cliente_Menu.png")); // NOI18N
        getContentPane().add(jbCliente);
        jbCliente.setBounds(230, 70, 120, 120);

        jbMatPrima.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Menu\\MateriaPrima_Menu.png")); // NOI18N
        jbMatPrima.setOpaque(false);
        getContentPane().add(jbMatPrima);
        jbMatPrima.setBounds(380, 70, 160, 120);

        jbMaterial.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Menu\\Material_Menu.png")); // NOI18N
        jbMaterial.setOpaque(false);
        getContentPane().add(jbMaterial);
        jbMaterial.setBounds(560, 70, 120, 120);

        jbServiço.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Menu\\Servico_Menu.png")); // NOI18N
        getContentPane().add(jbServiço);
        jbServiço.setBounds(710, 70, 120, 120);

        jbOrcamento.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Menu\\Orcamento_Menu.png")); // NOI18N
        getContentPane().add(jbOrcamento);
        jbOrcamento.setBounds(860, 70, 120, 120);

        lblFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Menu\\Fundo_Menu.png")); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1150, 620);

        setSize(new java.awt.Dimension(1164, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCliente;
    private javax.swing.JButton jbMatPrima;
    private javax.swing.JButton jbMaterial;
    private javax.swing.JButton jbOrcamento;
    private javax.swing.JButton jbServiço;
    private javax.swing.JButton jbUsuario;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables
}
