
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Aluno
 */
public class Servico extends javax.swing.JFrame {

    /**
     * Creates new form ex3
     */
    public Servico() {
        initComponents();
    }

    String usuario = "root";
    String senha = "";
    String url = "jdbc:mysql://127.0.0.1:3306/grafica";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        radAten = new javax.swing.JRadioButton();
        radAdmin = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServico = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Serviços");
        setResizable(false);
        getContentPane().setLayout(null);

        lblId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblId.setText("ID");
        getContentPane().add(lblId);
        lblId.setBounds(20, 120, 20, 15);

        txtId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtId);
        txtId.setBounds(100, 120, 255, 21);

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(20, 170, 40, 15);

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtNome);
        txtNome.setBounds(100, 160, 780, 21);

        lblValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblValor.setText("Valor");
        getContentPane().add(lblValor);
        lblValor.setBounds(20, 210, 28, 15);

        txtValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtValor);
        txtValor.setBounds(100, 210, 255, 21);

        lblDesc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDesc.setText("Descrição");
        getContentPane().add(lblDesc);
        lblDesc.setBounds(20, 260, 56, 15);

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 260, 1030, 110);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        radAten.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radAten.setText("Ativo");
        radAten.setOpaque(false);

        radAdmin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radAdmin.setText("Inativo");
        radAdmin.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radAdmin)
                    .addComponent(radAten))
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(radAten)
                .addGap(18, 18, 18)
                .addComponent(radAdmin))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(950, 130, 180, 100);

        tblServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Valor", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblServico);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 390, 1110, 280);

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Consultar_Servicos.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(20, 10, 70, 80);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Editar_Servicos.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(100, 10, 80, 80);

        btnAdicionar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cadastrar_Servicos.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(190, 10, 80, 80);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Limpar_Servicos.png"))); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(280, 10, 80, 80);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Excluir_Servicos.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(370, 10, 80, 80);

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Voltar_Servicos.png"))); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(460, 10, 80, 80);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundo_Cliente.png"))); // NOI18N
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1150, 690);

        setSize(new java.awt.Dimension(1166, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int cod_Servico = Integer.parseInt(txtId.getText());
        Double taxa = Double.parseDouble(txtValor.getText());
        String desc = txtDesc.getText();
        String nome = txtNome.getText();
        int tipo = 0;
        boolean aten = radAten.isSelected();
        boolean admin = radAdmin.isSelected();

        if (aten == true) {
            tipo = 1;
        } else {
            if (admin == true) {
                tipo = 2;
            }
        }

        String sql = "update servico set nome=?, descricao=?,taxa=? where cod_Servico=?";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setString(1, nome);
            comando.setString(2, desc);
            comando.setDouble(3, taxa);
        
            comando.setInt(4, cod_Servico);

            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Serviço alterado com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao editar dos dados de cadastro do serviço");
        }

        txtValor.setText(null);
        txtDesc.setText(null);
        txtNome.setText(null);
        txtId.setText(null);
        radAten.setText(null);
        radAdmin.setText(null);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String sql = "select * from servico order by nome";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            ResultSet resultado = comando.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) tblServico.getModel();

            //Limpar a tabela da tela
            //Capturar o total de linhas da tebela da tela.
            int totalDeLinhas = modelo.getRowCount();

            for (int p = 0; p < totalDeLinhas; p++) {
                //Remove a linha da tabela ba posição informada.
                modelo.removeRow(p);
            }

            while (resultado.next()) {
                Object[] linha = new Object[]{
                    resultado.getInt("cod_Servico"),
                    resultado.getString("descricao"),
                    resultado.getDouble("taxa"),
                    resultado.getString("nome")
                };

                modelo.addRow(linha);
            }
            txtValor.setText(null);
            txtDesc.setText(null);
            txtNome.setText(null);
            txtId.setText(null);
            radAten.setText(null);
            radAdmin.setText(null);

            resultado.close();
            comando.close();
            conexao.close();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na consulta de dados");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        //captura os dados digitados;F
        Double taxa = Double.parseDouble(txtValor.getText());
        String desc = txtDesc.getText();
        String nome = txtNome.getText();
        boolean aten = radAten.isSelected();
        boolean admin = radAdmin.isSelected();
        int tipo = 0;
        if (aten == true) {
            tipo = 1;
        } else {
            if (admin == true) {
                tipo = 2;
            }
        }

        String sql = "insert into servico (descricao, taxa, nome) values (?, ?, ?) ";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setString(3, nome);
            comando.setString(1, desc);
            comando.setDouble(2, taxa);

            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Serviço cadastrado com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na inserção dos dados cadastrais de usuáirio");
        }

        txtValor.setText(null);
        txtDesc.setText(null);
        txtNome.setText(null);
        txtId.setText(null);
        radAten.setText(null);
        radAdmin.setText(null);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtValor.setText(null);
        txtDesc.setText(null);
        txtNome.setText(null);
        txtId.setText(null);
        radAten.setText(null);
        radAdmin.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int cod_Servico = Integer.parseInt(txtId.getText());

        String sql = "delete FROM servico where cod_Servico=?";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setInt(1, cod_Servico);

            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Serviço removido com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na remoção dos dados do usuário");
        }

        txtValor.setText(null);
        txtDesc.setText(null);
        txtNome.setText(null);
        txtId.setText(null);
        radAten.setText(null);
        radAdmin.setText(null);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton radAdmin;
    private javax.swing.JRadioButton radAten;
    private javax.swing.JTable tblServico;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
