
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lízia Arantes
 */
public class MateriaPrima extends javax.swing.JDialog {

    /**
     * Creates new form MateriaPrima
     */
    public MateriaPrima(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    String usuario = "root";
    String senha = "";
    String url = "jdbc:mysql://127.0.0.1:3306/exercicio_11_05";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jlID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jlNomeMp = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jlQtd = new javax.swing.JLabel();
        txtqtd = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        radAten = new javax.swing.JRadioButton();
        radAdmin = new javax.swing.JRadioButton();
        jspTabela = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Matéria-Prima");
        setResizable(false);
        getContentPane().setLayout(null);

        jlID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlID.setText("ID");
        getContentPane().add(jlID);
        jlID.setBounds(20, 140, 20, 14);

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtID);
        txtID.setBounds(120, 130, 700, 30);

        jlNomeMp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlNomeMp.setText("Matéria-Prima");
        getContentPane().add(jlNomeMp);
        jlNomeMp.setBounds(20, 180, 90, 14);

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtnome);
        txtnome.setBounds(120, 170, 700, 30);

        jlQtd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlQtd.setText("Quantidade");
        getContentPane().add(jlQtd);
        jlQtd.setBounds(20, 220, 70, 14);
        getContentPane().add(txtqtd);
        txtqtd.setBounds(120, 210, 700, 30);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        radAten.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radAten.setSelected(true);
        radAten.setText("Ativo");
        radAten.setOpaque(false);

        radAdmin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radAdmin.setText("Inativo");
        radAdmin.setOpaque(false);
        radAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radAdmin)
                    .addComponent(radAten))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(radAten)
                .addGap(18, 18, 18)
                .addComponent(radAdmin)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(900, 120, 230, 120);

        jTabela.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Matéria - Prima", "Quantidade", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabelaMousePressed(evt);
            }
        });
        jspTabela.setViewportView(jTabela);

        getContentPane().add(jspTabela);
        jspTabela.setBounds(20, 260, 1110, 400);

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundos_Icones_Materiais\\Consultar_Materiais.png")); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(20, 10, 80, 80);

        btnAdicionar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundos_Icones_Materiais\\Cadastrar_Materiais.png")); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(200, 10, 80, 80);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundos_Icones_Materiais\\Editar_Materiais.png")); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(110, 10, 80, 80);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundos_Icones_Materiais\\Excluir_Materiais.png")); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(380, 10, 80, 80);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundos_Icones_Materiais\\Limpar_Materiais.png")); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(290, 10, 80, 80);

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundos_Icones_Materiais\\Voltar_Materiais.png")); // NOI18N
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(470, 10, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundos_Icones_Materiais\\Fundo_Materiais.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 690);

        setSize(new java.awt.Dimension(1165, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtnome.setText(null);
        txtqtd.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        //captura os dados digitados;F
        int qtd = Integer.parseInt(txtqtd.getText());
        String nome = txtnome.getText();

        String sql = "insert into materiaprima values (?, ?) ";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setString(1, nome);
            comando.setInt(2, qtd);

            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Matéria-prima cadastrado com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na inserção dos dados cadastrais de matéria-prima");
        }

        txtnome.setText(null);
        txtqtd.setText(null);

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String sql = "select * from materiaprima order by nome";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            ResultSet resultado = comando.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();

            //Limpar a tabela da tela
            //Capturar o total de linhas da tebela da tela.
            int totalDeLinhas = modelo.getRowCount();

            for (int p = 0; p < totalDeLinhas; p++) {
                //Remove a linha da tabela ba posição informada.
                modelo.removeRow(p);
            }

            while (resultado.next()) {
                Object[] linha = new Object[]{
                    resultado.getInt("id"),
                    resultado.getString("nome"),
                    resultado.getInt("qtd"),};

                modelo.addRow(linha);
            }

            txtnome.setText(null);
            txtqtd.setText(null);

            resultado.close();
            comando.close();
            conexao.close();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na consulta de matéria-prima");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = Integer.parseInt(txtID.getText());

        String sql = "delete materiaprima where id=?";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setInt(1, id);

            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "matéria-prima removida com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro na remoção dos dados de matéria-prima");
        }

        txtnome.setText(null);
        txtqtd.setText(null);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int qtd = Integer.parseInt(txtqtd.getText());
        int id = Integer.parseInt(txtID.getText());
        String nome = txtnome.getText();

        String sql = "update materiaprima set nome=?, qtd=?,where id=?";

        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);

            PreparedStatement comando = conexao.prepareStatement(sql);

            comando.setString(1, nome);
            comando.setInt(2, qtd);
            comando.setInt(3, id);
            comando.executeUpdate();

            JOptionPane.showMessageDialog(null, "Matéria-prima alterada com sucesso!");

            comando.close();
            conexao.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao editar dos dados de cadastro de Matéria-Prima");
        }

        txtnome.setText(null);
        txtqtd.setText(null);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jTabelaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMousePressed
        //getSelectRow - capturar a posição da linha clicada.
        int linha = jTabela.getSelectedRow();

        //getValueAt - Captura um valor em uma linha e coluna especificada.
        int id = (int) jTabela.getValueAt(linha, 0);
        String nome = (String) jTabela.getValueAt(linha, 1);
        int qtd = (int) jTabela.getValueAt(linha, 2);

        txtID.setText(String.valueOf(id));
        txtnome.setText(nome);
        txtqtd.setText(String.valueOf(qtd));
    }//GEN-LAST:event_jTabelaMousePressed

    private void radAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MateriaPrima dialog = new MateriaPrima(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlNomeMp;
    private javax.swing.JLabel jlQtd;
    private javax.swing.JScrollPane jspTabela;
    private javax.swing.JRadioButton radAdmin;
    private javax.swing.JRadioButton radAten;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtqtd;
    // End of variables declaration//GEN-END:variables
}
