
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lízia Arantes
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlUsuario = new javax.swing.JLabel();
        jformatCPF = new javax.swing.JFormattedTextField();
        jlSenha = new javax.swing.JLabel();
        jpwdSenha = new javax.swing.JPasswordField();
        jbLog = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(null);

        jlUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlUsuario.setText("Usuário (CPF)");
        getContentPane().add(jlUsuario);
        jlUsuario.setBounds(90, 120, 79, 15);

        try {
            jformatCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jformatCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jformatCPFActionPerformed(evt);
            }
        });
        getContentPane().add(jformatCPF);
        jformatCPF.setBounds(180, 110, 260, 30);

        jlSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlSenha.setText("Senha");
        getContentPane().add(jlSenha);
        jlSenha.setBounds(90, 170, 36, 15);

        jpwdSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwdSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jpwdSenha);
        jpwdSenha.setBounds(180, 160, 260, 30);

        jbLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbLog.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Login\\Botao_Login.png")); // NOI18N
        jbLog.setOpaque(false);
        jbLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLogActionPerformed(evt);
            }
        });
        getContentPane().add(jbLog);
        jbLog.setBounds(180, 210, 100, 50);

        jbCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Login\\Cancela_Login.png")); // NOI18N
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbCancelar);
        jbCancelar.setBounds(340, 210, 100, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\marqu\\OneDrive\\Documentos\\Fatec\\5º Semestre\\Laboratório de Engenharia_Elaine\\Telas\\Fundo_Icones_Login\\Fundo_Login.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 281);

        setSize(new java.awt.Dimension(616, 319));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpwdSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwdSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpwdSenhaActionPerformed

    private void jbLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLogActionPerformed
        
    }//GEN-LAST:event_jbLogActionPerformed

    private void jformatCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jformatCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jformatCPFActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbLog;
    private javax.swing.JFormattedTextField jformatCPF;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPasswordField jpwdSenha;
    // End of variables declaration//GEN-END:variables
}
